

<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<%@ taglib prefix="s" uri="/struts-tags" %>
<%@ page import="java.text.SimpleDateFormat" %>
<%@ page import="java.util.List" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">



<html>
    <head>
                <!-- HTTP 1.1 -->
        <meta http-equiv="Cache-Control" content="no-store"/>
        <!-- HTTP 1.0 -->
        <meta http-equiv="Pragma" content="no-cache"/>
        <!-- Prevents caching at the Proxy Server -->
        <meta http-equiv="Expires" content="0"/>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <link rel="icon" href="/maa/images/favicon.ico"/>
        <title>rx  - Doctor Details </title>

        <link rel="stylesheet" type="text/css" media="all" href="/maa/css/rx.css" />
      	<link rel="stylesheet" type="text/css" href="/maa/commonyui/build/reset/reset.css" />
		<link rel="stylesheet" type="text/css" href="/maa/commonyui/build/fonts/fonts.css" />
		<style>
			html {
				background:none;
			}
		</style>
        <script type="text/javascript" src="/maa/javascripts/calender.js"></script>
        <script type="text/javascript" src="/maa/script/calendar.js" ></script>
		<script type="text/javascript" src="/maa/javascripts/validations.js"></script>
		<script type="text/javascript" src="/maa/javascripts/SASvalidation.js"></script>
		<script type="text/javascript" src="/maa/javascripts/dateValidation.js"></script>
	
		<script type="text/javascript" src="/maa/commonyui/build/yahoo/yahoo.js"></script>
		<script type="text/javascript" src="/maa/commonyui/build/dom/dom.js"></script>
		<script type="text/javascript" src="/maa/commonyui/build/autocomplete/autocomplete-debug.js"></script>
		<script type="text/javascript" src="/maa/commonyui/build/event/event-debug.js"></script>
		<script type="text/javascript" src="/maa/commonyui/build/animation/animation.js"></script>
		<script type="text/javascript" src="/maa/commonjs/ajaxCommonFunctions.js"></script>
		
		<script type="text/javascript" src="/maa/script/jsCommonMethods.js"></script>
		
    </head>
    
<body>
	

<div class="commontopyellowbg">Administration</div>
<div class="commontopbluebg"><div class="commontopdate">Today is: 
	<span class="bold" style="color:black"><%=new SimpleDateFormat("dd/MM/yyyy").format(new java.util.Date())%>
	</span></div>Welcome <span class="bold" style="color:#cccccc"><s:property value="#session.UserName"/></span>
</div>
<div class="commontopbreadc" id="breadcrumb">&nbsp;<!--%=breadCrumb%> --></div>
<!--  script>
	if (document.getElementById('breadcrumb').innerHTML == '') {
		document.getElementById('breadcrumb').innerHTML = ''+  " > "+document.title;
	}
</script -->
	
 
	<br/>
	<table align="center">
		<tr> 
			<td>
				<div id="main">
		  			<div id="m2">
		  				<div id="m3">
		  					<div align="center">
		  						<s:form theme="simple" name="viewChemist" method="post" onsubmit="return validation()">
			<table align="center" id="getAllDetails" name="getAllDetails">
				<table align="center" class="tableStyle">
					<tr>
						<td class="tableheader" align="middle" width="728" height="6">Chemist Details</td>
					</tr>
					<tr>
						<td colspan="4">&nbsp;</td>
					</tr>
			</table>
			<br/><br/>
			<table align="center"  class="tableStyle">
				<s:iterator value="chemListForViewAndEdit">
				<tr>
					<td  class="labelcell" width="40%" height="23" >Chemist ID <font class="ErrorText" size="-2">(Autogenerated)</font></td>
					<td  class="labelcell" align="left" width="40%" height="23" background="yellow">
						<s:textfield name="chemist_id" value="%{chemist_id}" id="chemist_id" class="ControlText" readonly="true"/>
					</td>				
				
					<td class="labelcell"  width="40%" height="23" >Chemist Name<font class="ErrorText">*</font></td>
					<td class="labelcell"  align="left" width="40%" height="23" >
						<s:textfield name="chemist_name" value="%{chemist_name}" id="chemist_name" class="ControlText" readonly="true"/>
					</td>
					
					<td  class="labelcell" width="40%" height="23" >Contact Number<font class="ErrorText">*</font></td>
					<td  class="labelcell" align="left" width="40%" height="23" >
						<s:textfield name="contact_no" value="%{contact_no}" id="contact_no" class="ControlText" readonly="true"/>
					</td>
				</tr>
				<tr>
					<td class="labelcell" width="40%" height="23"><s:label value="Territory ID" /></td>
					<td class="labelcell" align="left" width="40%" height="23">
						<s:select theme="simple" name="ter_id" value="%{ter_id}" id="ter_id" list="territoryList" listKey="ter_id" listValue="territory" headerKey="" headerValue="---Select---" cssClass="ControlText" disabled="true"/>
					</td>				
				
					<td class="labelcell"  width="40%" height="23" >Email ID</td>
					<td class="labelcell"  align="left" width="40%" height="23" >
						<s:textfield name="email_id" value="%{email_id}" id="email_id" class="ControlText" readonly="true"/>
					</td>	
					<td  class="labelcell" width="40%" height="23" >Address Line 1<font class="ErrorText">*</font></td>
					<td  class="labelcell" align="left" width="40%" height="23" >
						<s:textfield name="address_1" value="%{address_1}" id="address_1" class="ControlText" readonly="true"/>
					</td>
				</tr>
				
				
				<tr>			
					<td class="labelcell"  width="40%" height="23" >Address Line 2</td>
					<td class="labelcell"  align="left" width="40%" height="23" >
						<s:textfield name="address_2" value="%{address_2}" id="address_2" class="ControlText" readonly="true"/>
					</td>
					
					<td  class="labelcell" width="40%" height="23" >City<font class="ErrorText">*</font></td>
					<td  class="labelcell" align="left" width="40%" height="23" >
						<s:select theme="simple" name="city_id" value="%{city_id}" id="city_id" cssClass="ControlText" list="cityList" listKey="cityId" listValue="cityName" headerKey="" headerValue="--Select--" disabled="true"/>
					</td>				
				
					<td class="labelcell"  width="40%" height="23" >State</td>
					<td class="labelcell"  align="left" width="40%" height="23" >
						<s:select theme="simple" name="state_id" value="%{state_id}" id="state_id" cssClass="ControlText" list="stateList" listKey="stateId" listValue="stateName" headerKey="" headerValue="--Select--" disabled="true"/>
					</td>
					
				</tr>
				
				<tr>
					<td class="labelcell"  width="40%" height="23" >Is Active</td>
					<td class="labelcell"  align="left" width="40%" height="23" >
						<s:checkbox name="active" value="%{active}" disabled="true" id="active" cssClass="ControlText"/>
					</td>
					
				</tr>
				</s:iterator>				
			</table>
			<br/><br/>
			<table align="center" class="tableStyle" cellspacing="2">
				<tr>
					<td>
					<input type="button" value="CLOSE" id="closeButton" name="closeButton" onclick="window.close();" />
					</td>					
					<td>
					<input type="button" value="EDIT" id="button" name="Submit" onclick="return editChemist();"/>
					</td>					
					
				</tr>			
			</table>
			</table>
		</s:form>
		  					</div>
						</div>
					</div>
				</div>
			</td>
		</tr>
	</table>	
</body>
<script type="text/javascript">
function editChemist(){
	
	document.viewChemist.action='/maa/editChemist';
	document.viewChemist.submit();
}
</script>
</html>
